name: Convert Markdown to PDF

on:
  push:
    paths:
    - '**.md'
    - .github/workflows/main.yml

jobs:
  convert_md:  
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2.0.0
      with:
        fetch-depth: 1
    - name: Convert Markdown File
      uses: pharbison/md-to-pdf@master
      with:
        MD_SRC: './export/patrick-harbison-resume.md'
        PDF_DST: './export/patrick-harbison-resume.pdf'
        OPTS: '-V geometry:margin=1in'
        LINE_BREAK: '42'
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v1.6.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COMMIT_MESSAGE: Add .pdf file.